spring:
  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: movie
     mongodb:
      host: dds-uf6ded63e5e9a4441635-pub.mongodb.rds.aliyuncs.com
      port: 3717
      authentication-database: admin
      database: movie
      username: root
      password: '***REMOVED***'
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      enabled: true

server:
  port: 8080
  servlet:
    context-path: /api
